### ISSUE TITLE
activate SSO with ADFS using App service

### ISSUE THREAD

**Issue by NDebbou** [SaarCohen/GeminiAzure#3]
Hello Saar,

We try to install Gemini on Azure Web App and to record it to our ADFS.
• ADFS On Premises with thawste root certificates 
• Azure app service with native certificates 

The Azure website is working fine within Forms Authentication, but if we activate the windows authentication and ADFS configuration, we get an error message. The error we're basically getting is:  certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider

For more information : https://social.msdn.microsoft.com/Forums/en-US/a38d1350-59b0-4a12-94f8-cc0a07257b88/validating-certificate-trust-chain-on-azure-website-communicating-with-our-adfs-with-ssl?forum=windowsazurewebsitespreview

CAn you help us to resolve this issue ?

Thanks,
BR,
Nabil Debbou

**Comment by SaarCohen** [comment]
Please contact support@countersoft.com for any support issues.
